[package]
name = "keyboard-color-chooser"
version = "0.1.0"
authors = ["Aaron Honeycutt <honeycuttaaron3@gmail.com>"]
edition = "2018"

[dependencies.gtk]
version = "0.7.0"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]
